// mypages.js
// 2025-02-24 by go
// HTML templates generating functions

export function genMainPage(data){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <title>Escola de Música</title>
            <link rel="stylesheet" type="text/css" href="w3.css"/>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-red">
                    <h1>Escola de Música</h1>
                </header>

                <div class="w3-container">
                    <ul class="w3-ul">
                        <li>
                            <a href="/alunos">Lista de Alunos</a>
                        </li>
                        <li>
                            <a href="/cursos">Lista de Cursos</a>
                        </li>
                        <li>
                            <a href="/instrumentos">Lista de Instrumentos</a>
                        </li>
                    </ul>
                </div>
                
                <footer class="w3-container w3-red">
                    <h5>Generated by Guilherme Oliveira in ${data}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

export function genAlunosPage(lalunos, data){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <title>Escola de Música</title>
            <link rel="stylesheet" type="text/css" href="w3.css"/>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h1>Lista de Alunos</h1>
                </header>

                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th>
                            <th>Nome</th>
                        </tr>`
    lalunos.forEach(aluno => {
        pagHTML += `
        <tr>
            <td><a href="/alunos/${aluno.id}">${aluno.id}</a></td>
            <td><a href="/alunos/${aluno.id}">${aluno.nome}</a></td>
        </tr>
        `
    });

    pagHTML += `  
                    </table>
                </div>
                
                <footer class="w3-container w3-purple">
                    <h5>Generated by Guilherme Oliveira in ${data}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

export function genCursosPage(lcursos, data){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <title>Escola de Música</title>
            <link rel="stylesheet" type="text/css" href="w3.css"/>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-blue">
                    <h1>Lista de Cursos</h1>
                </header>

                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th>
                            <th>Designação</th>
                        </tr>`
    lcursos.forEach(curso => {
        pagHTML += `
        <tr>
            <td><a href="/cursos/${curso.id}">${curso.id}</a></td>
            <td><a href="/cursos/${curso.id}">${curso.designacao}</a></td>
        </tr>
        `
    });

    pagHTML += `  
                    </table>
                </div>
                
                <footer class="w3-container w3-blue">
                    <h5>Generated by Guilherme Oliveira in ${data}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

export function genInstrumentosPage(linstrumentos, data){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <title>Escola de Música</title>
            <link rel="stylesheet" type="text/css" href="/w3.css"/>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-orange">
                    <h1>Lista de Instrumentos</h1>
                </header>

                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th>
                            <th>Intrumento</th>
                        </tr>`
    linstrumentos.forEach(marca => {
        pagHTML += `
        <tr>
            <td><a href="/instrumentos/${marca.id}">${marca.id}</a></td>
            <td><a href="/instrumentos/${marca.id}">${marca['#text']}</a></td>
        </tr>
        `
    });

    pagHTML += `  
                    </table>
                </div>
                
                <footer class="w3-container w3-orange">
                    <h5>Generated by Guilherme Oliveira in ${data}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

export function genAlunoPage(aluno, data){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <title>Escola de Música</title>
            <link rel="stylesheet" type="text/css" href="w3.css"/>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h1>${aluno.nome}</h1>
                </header>

                <div class="w3-container">
                    <p>Número: ${aluno.id}</p>
                    <p>Nome: ${aluno.nome}</p>
                    <p>Data de Nascimento: ${aluno.dataNasc}</p>
                    <p>Curso: ${aluno.curso}</p>
                    <p>Ano do Curso: ${aluno.anoCurso}</p>
                    <p>Instrumento: ${aluno.instrumento}</p>
                </div>
                
                <footer class="w3-container w3-purple">
                    <h5>Generated by Guilherme Oliveira in ${data}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

export function genCursoPage(curso, data){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <title>Escola de Música</title>
            <link rel="stylesheet" type="text/css" href="w3.css"/>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-blue">
                    <h1>${curso.designacao}</h1>
                </header>

                <div class="w3-container">
                    <p>Id: ${curso.id}</p>
                    <p>Designação: ${curso.designacao}</p>
                    <p>Duração: ${curso.duracao}</p>
                    <p>Instrumento: <a href="/instrumentos/${curso.instrumento.id}">${curso.instrumento['#text']}</a></p>
                    <p>Docente: ${curso.docente}</p>
                </div>
                
                <footer class="w3-container w3-blue">
                    <h5>Generated by Guilherme Oliveira in ${data}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

export function genInstrumentoPage(instrumento, lalunos, data){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <title>Escola de Música</title>
            <link rel="stylesheet" type="text/css" href="w3.css"/>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-blue">
                    <h1>${instrumento['#text']}</h1>
                </header>

                <div class="w3-container">
                    <p>Id: ${instrumento.id}</p>
                    <p>Instrumento: ${instrumento['#text']}</p>
                    <p>Alunos:</p>
                    <ul>`
    lalunos.forEach(aluno => {
        pagHTML += `
        <li><a href="/alunos/${aluno.id}">${aluno.id} - ${aluno.nome}</a></li>
        `
    })
    pagHTML += `  
                    </ul>
                </div>
                
                <footer class="w3-container w3-blue">
                    <h5>Generated by Guilherme Oliveira in ${data}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}